### ISSUE TITLE
Altair documentation

### ISSUE THREAD

**Issue by ERDataDoc** [ellisonbg/altair#159]
I am wondering if there is documentation of all of the features of Altair.  I am looking specifically now for the options that exist for the "mark_<  >" method of the Chart object.  The Aggregate Operations have a listing (I am assuming it is a complete listing) of all the choices.  I don't see that for the mark_ method.  Since this is a statistical visualization API, I am wondering about boxplots, since these are sometimes useful during exploratory data analysis.  

Thank you.

**Comment by ERDataDoc** [comment]
OK, I answered part of the question myself, I found the mark methods farther down the Introduction notebook.

**Comment by jakevdp** [comment]
Hi @ERDataDoc – The best way to find the options available to the function is to use the documentation string.  For example, in IPython/Jupyter Notebook you can type
```python
Chart.mark_<TAB>
```
to see all the available mark methods, and e.g.
```python
Chart.mark_point?
```
to see the documentation for the method, which includes a description of all the available options.

Additionally, since Altair is built around Vega-Lite, the Vega-Lite documentation will be helpful in answering questions about various available properties. Here's the [Vega-Lite mark configuration docs](https://vega.github.io/vega-lite/docs/config.html). Scroll down to "Mark Configuration" there.

Regarding Box Plots, we don't have an easy way to make those – yet. But the Vega-Lite project is [actively discussing](https://github.com/vega/vega-lite/issues/220) this, and as these kinds of features are added to it we will make them accessible from Altair as well.

**Comment by ERDataDoc** [comment]
Thank you for that update.  I went back and was successful at using the tab completion and help functions.  Thanks for your help.  Looking forward to getting to know Altair better.
