### ISSUE TITLE
Set values for time axis

### ISSUE THREAD

**Issue by iaindillingham** [ellisonbg/altair#187]
I'm unclear as to how I might set the values for a time axis. I'm using `Axis` as follows...

`Axis(title=my_title, values=my_values)`

...and have tried setting `my_values` to a list of ISO formatted strings, `datetime` objects, `datetime64` objects (np) and a `DatetimeIndex` object (pd). In each case, the stacktrace indicates that a `float` is required.

Thanks for any help in advance. I appreciate that this is less an issue and more a request for assistance, but there isn't an Altair discussion forum.

**Comment by jakevdp** [comment]
Hi @iaindillingham – great question, and after poking around a bit I don't have a good answer.

The Vega-Lite schema specifies that ``Axis.values`` should be a list of numbers... Altair interprets number as something convertible to floating point. Maybe @kanitw can comment on how this can best be accomplished in Vega-Lite.

**Comment by jheer** [comment]
@kanitw can speak to the vega-lite schema issues.

In the underlying Vega implementation UNIX time stamps (long integers,
which fall under type "number" in JavaScript) can stand in for JS Date
objects. So one path to try would be outputting Date values as time stamps
when generating the VL JSON from Altair. Of course, the scale transform
driving the axis would need to be a Date-type (temporal) scale to interpret
the values correctly.

**Comment by jakevdp** [comment]
Thanks @jheer – going off that, I was able to set time axes by converting pandas dates to microseconds-since 1970:

```python
import pandas as pd
import numpy as np

data = pd.DataFrame({'x': pd.date_range('2015-01', periods=10, freq='M'),
                     'y': np.sin(np.arange(10))})

unix_dates = list(data['x'].astype(int) // 10**6)

dates = pd.to_datetime(['2015-03-15', '2015-05-15', '2015-07-15']).astype(int) / 10 ** 6

Chart(data).mark_line().encode(
    x=X('x', axis=Axis(values=list(dates))),
    y='y'
)
```
![vega 15](https://cloud.githubusercontent.com/assets/781659/18174355/244a8956-7022-11e6-88d7-7ee0e3f8157c.png)

If this is the best way to do it, it might be useful to automatically do this kind of conversion of date values on the Python side.

**Comment by jheer** [comment]
This is probably the best way, seeing as how JSON has no built-in way of
expressing Date value literals.

**Comment by kanitw** [comment]
This reminds me that we should support our [DateTime Definition object](https://vega.github.io/vega-lite/docs/transform.html#datetime) (that we introduced for temporal filter) for axis/legend's `values` as well (https://github.com/vega/vega-lite/issues/1516).  So this will be reasonable to use when people use Vega-Lite from JSON.  

That said, I think from Altair's perspective, I think automatically date conversion to timestamp would be better.   :) 

> probably oweing to differing treatments of midnight between pandas and vega-lite.

Possibly because the timestamp is UTC but our label displays local time.  
We'll have to work on support for UTC (https://github.com/vega/vega-lite/issues/446).

cc: @domoritz

**Comment by iaindillingham** [comment]
Hello everyone,

Thank you all for your time. It's reassuring to find such a committed bunch of core developers!

I followed @jakevdp and passed timestamps to `Axis`. Rather than hard-coding dates, I used [`pd.date_range`][1] as follows:

```python
date_min = '2016-01-01'
date_max = '2016-02-01'
my_values = list(pd.date_range(date_min, date_max, freq='W-MON').astype(int) / 10 ** 6)
```
The curious can find the associated notebook [here][2]. (It's a quick exploration of bike usage in Bath, UK, which I prepared for [an upcoming hack day][3].)

[1]: http://pandas.pydata.org/pandas-docs/stable/generated/pandas.date_range.html
[2]: https://github.com/iaindillingham/nextbike/blob/master/num_bikes_by_location.ipynb
[3]: https://www.bathhacked.org/celebrate-the-city/celebrate-the-city/
