### ISSUE TITLE
Treemap

### ISSUE THREAD

**Issue by rornor** [ellisonbg/altair#204]
Hi,

vega has treemap spec, as in this example: http://trifacta.github.io/vega/editor/index.html?spec=treemap

I know altair uses vega-lite, but though to check if it is possible to use altair for generating treemap graph?

**Comment by jakevdp** [comment]
I don't think that's supported in Vega-Lite at this time.

**Comment by rornor** [comment]
Thanks for your quick response.

**Comment by badilla** [comment]
I saw vega-lite has something called Mosaic Chart, isn't this close to a treemap ?
https://vega.github.io/vega-lite/examples/rect_mosaic_labelled_with_offset.html

**Comment by jakevdp** [comment]
> I saw vega-lite has something called Mosaic Chart

That makes use of the stack transform, which is only available in Vega-Lite 3, which is not yet released and thus not yet supported by Altair.

But once Altair 3.0 comes out, this would be a useful example to have.

**Comment by brainstorm** [comment]
Seems to be supported in Vega:

https://vega.github.io/vega/examples/treemap/

But not sure it's implemented in Altair yet, since I cannot find it in the plot gallery for Altair v3.0.0:

https://altair-viz.github.io/gallery/

I'm actually looking after the most typical disk space utilization plot, Sunburst, as hinted in https://github.com/altair-viz/altair/issues/382, but I'm not finding any examples/references so far.

**Comment by adxrgh** [comment]
looking for this too

**Comment by lucasvw** [comment]
+1

**Comment by jakevdp** [comment]
Treemap is not supported in Vega-lite, so it is not available in Altair.

**Comment by lucasvw** [comment]
Ah ok, [vega](https://vega.github.io/vega/examples/treemap/) `!=` vega-lite. That's a shame, but understood. thnx
