### ISSUE TITLE
Cannot import the lightning renderer

### ISSUE THREAD

**Issue by aggFTW** [ellisonbg/altair#67]
I'm getting latest altair and installing it following instructions. I'm running the server like so:

```
The version of the notebook server is 3.2.0-8b0eef4 and is running on:
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42) 
[GCC 4.2.1 (Apple Inc. build 5577)]
```

When I try to run the BasicExample notebook with `alt.use_renderer('lightning')`, I get the following exception:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-6d2e0a8f478e> in <module>()
----> 1 alt.use_renderer('lightning')

/Users/alexgg/anaconda/lib/python2.7/site-packages/altair-0.0.1-py2.7.egg/altair/api.pyc in use_renderer(r)
    437     else:
    438         if r in _renderers:
--> 439             _renderer = _renderers[r]()
    440         else:
    441             raise ValueError('renderer could not be found: {0}').format(r)

/Users/alexgg/anaconda/lib/python2.7/site-packages/altair-0.0.1-py2.7.egg/altair/api.pyc in _get_lightning_renderer()
    413 
    414 def _get_lightning_renderer():
--> 415     from .lgn import LightningRenderer
    416     return LightningRenderer()
    417 

build/bdist.macosx-10.5-x86_64/egg/altair/lgn.py in <module>()

build/bdist.macosx-10.5-x86_64/egg/altair/lightning.py in <module>()

NameError: name 'Lightning' is not defined
```

Any ideas?
Thanks!

**Comment by aggFTW** [comment]
@ellisonbg might know what's going on

**Comment by ellisonbg** [comment]
The last line of this traceback:

`build/bdist.macosx-10.5-x86_64/egg/altair/lightning.py in <module>()`

shows that you will have the old lightning.py or lightning.pyc file around on your file system. The new file `lgn.py` is trying to import `lightning` and finding that file rather than the actual main lightning-python package.

Here are steps to fix this:

1. `pip uninstall altair`
2. Remove the build directory from the altair dir.
3. Make sure that you remove the old lightning.py/pyc from the directory that has the new lgn.py file.
4. Now pip install again `pip install -e .` for a symlinked dev install so you don't have to reinstall when you make changes.

**Comment by aggFTW** [comment]
Thanks! That did the trick.

Does step 4 mean that we don't need to install altair with the setup.py script included?

**Comment by ellisonbg** [comment]
`pip install -e .` will actually run the setup.py for you, but do
everything you need to symlink things so you don't have to reinstall each
time you change something.

On Wed, Oct 14, 2015 at 1:33 AM, Alejandro Guerrero Gonzalez <
notifications@github.com> wrote:

> Thanks! That did the trick.
>
> Does step 4 mean that we don't need to install altair with the setup.py
> script included?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ellisonbg/altair/issues/67#issuecomment-147939895>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by aggFTW** [comment]
Got it. Thanks!
