### ISSUE TITLE
Syntax Questions / Comments

### ISSUE THREAD

**Issue by kanitw** [ellisonbg/altair#95]
I skim through the notebooks in the notebooks folder. 

1) I wonder why `Scatterplot.ipynb` and `SimpleBarChart.ipynb` have  `x=`, `y=` in the `encode()` function.  (`x=X('Horsepower')`) seems somewhat redundant compared to `BasicExample.ipynb`, which do not require `x=` prefix.   That said, `x=` might be useful in the sense that people shouldn't assign multiple `fieldDefs` to the same channel except `detail`.    

```
Layer(data).encode(     x=X('Horsepower'),     y=Y('Miles_per_Gallon') ).point()
```

2) Note that using `Layer` as the base object might introduce future conflict with our `layer` composition operator.

**Comment by jakevdp** [comment]
These are still works in progress, and need to be cleaned up.

The simplest way to call it is ``x='Horsepower'``. ``x=X('Horsepower')`` exists so you can pass other attributes to the channel, such as ``X('Horsepower', bin=Bin(maxbins=10))``

**Comment by jakevdp** [comment]
I'm not totally married to ``Layer`` as the base object, though I don't have a better suggestion at the moment. Any thoughts on that?

**Comment by ellisonbg** [comment]
@kanitw I agree that the `x=X(...)` version is redundant. I think we should accept that but not use it in the code in favor of the `x='foo'` and `X('foo')` versions.

In terms of the naming of `Layer`, we did pick that with @jheer with the new layering stuff in mind. The idea is that the object we are now calling `Layer` is essentially the objet that will be used for individual layers. We can change it if there is a name that better makes sense. One thing that we are finding is that the defs in the JSON spec end up becoming class names in out Python API. Because of this, it is pretty important to think about their naming, even though those names are not actually use in the live JSON objects.

Thought on what you will call this object in the vegalite defs, once you introduce layering?

**Comment by ellisonbg** [comment]
I opened this issue on vega-lite about more general renaming questions:

https://github.com/vega/vega-lite/issues/1377

**Comment by ellisonbg** [comment]
Closing this as no action needed for now...
